# Generated by Django 3.1.2 on 2022-12-01 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bledy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lider_dzial',
            name='dzial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bledy.gruparobocza'),
        ),
    ]
