# Generated by Django 3.2.9 on 2022-12-04 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bledy', '0002_auto_20221201_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lider_dzial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lider', to=settings.AUTH_USER_MODEL),
        ),
    ]
